# Generated by Django 5.2.8 on 2025-11-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='cover_image',
            field=models.ImageField(upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
